In [ ]:
'''ПРАКТИЧНА РОБОТА 1.
Вступ до машинного навчання. Елементи лінійної алгебри.
Корчага Тетяна Анатоліївна 
ФІТ 4-6
Варіант 11'''

In [1]:
import numpy as np

In [2]:
'''1.	Створіть одновимірний масив (вектор) зі збільшувальною арифметичною послідовністю,
де кожне наступне число більше попереднього на 5, починаючи з 3, та виведіть його значення.'''

a = np.arange(3, 100, 5)
print(a)


[ 3  8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93 98]


In [3]:
'''2.	Створіть двовимірний масив (матрицю) розміром 3x3, 
заповніть його добутками кожного числа та його попереднього, починаючи з 1, та виведіть його значення.'''

a = np.zeros((3, 3), dtype=int)

# Заповнюємо матрицю добутками чисел та їх попередніх
for i in range(3):
    for j in range(3):
        value = (i + 1) * (j + 1)
        a[i][j] = value
print(a)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [4]:
'''3.	Створіть масив розміром 8x8, заповніть його випадковими натуральними числами від 1 до 100 
та знайдіть середнє арифметичне його елементів.'''

a = np.random.randint(1, 101, (8, 8))

b = np.mean(a)

print("Масив:\n", a)
print("\nСереднє арифметичне = ", round(b,2))

Масив:
 [[ 56  68 100  39  13  56  80  82]
 [ 98  59  53  22  73  40  24  11]
 [ 51  80  98   6  63  28 100  19]
 [ 63  15  90  57  54   3  32  10]
 [ 66  36   4  78  72  66  45  29]
 [ 37   7  48  94  59   7  21  14]
 [100  21   3  56  40  86  47  62]
 [ 80  60  14  44  95  95  16  32]]

Середнє арифметичне =  49.64


In [5]:
'''4.	Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 
та знайдіть кількість елементів, що більше 0.5.'''

a = np.random.rand(4, 4)
k = np.sum(a > 0.5)
print("Масив:\n", a)
print("\nКількість елементів, що більше 0.5 = ", k)

Масив:
 [[0.95245908 0.94381189 0.15086282 0.97211477]
 [0.92596107 0.52752603 0.42536185 0.61301575]
 [0.68962705 0.69525886 0.0603447  0.55110769]
 [0.27176402 0.63258944 0.85643267 0.33675629]]

Кількість елементів, що більше 0.5 =  11


In [6]:
'''5.	Створіть два одновимірних масиви розміром 7, 
заповніть їх випадковими цілими числами від -15 до 15 
та виконайте на них поелементні операції додавання, віднімання та множення.'''

a = np.random.randint(-15, 16, size=7)
b = np.random.randint(-15, 16, size=7)

print("a = ", a)
print("b = ", b)

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)

a =  [  0   5  -6   3  -8  10 -11]
b =  [  5 -13 -12 -15  -3  -1 -15]
a + b =  [  5  -8 -18 -12 -11   9 -26]
a - b =  [-5 18  6 18 -5 11  4]
a * b =  [  0 -65  72 -45  24 -10 165]


In [7]:
'''6.	Створіть два вектори розміром 7, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.'''
a = np.random.randint(1, 11, size=7)
b = np.random.randint(3, 30, size=7)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Скалярний добуток векторів = ", dot_a_b)

a =  [8 1 2 9 6 3 2]
b =  [ 5 22 10  5 24 19 20]
Скалярний добуток векторів =  368


In [8]:
'''7.	Створіть дві матриці розміром 4x2 та 2x5, 
заповніть їх випадковими цілими числами в діапазоні від 1 до 12 та перемножте їх між собою.'''

a = np.random.randint(1, 13, size=(4, 2))
b = np.random.randint(1, 13, size=(2, 5))

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Результат множення матриць:")
print(dot_a_b)

a =  [[ 5  2]
 [ 6  3]
 [ 1 11]
 [ 8  1]]
b =  [[ 6 12  2 11  8]
 [10  4  3  3  6]]
Результат множення матриць:
[[ 50  68  16  61  52]
 [ 66  84  21  75  66]
 [116  56  35  44  74]
 [ 58 100  19  91  70]]


In [9]:
'''8.	Створіть матрицю розміром 2x2, 
заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.'''

a = np.random.randint(1, 13, size=(2, 2))
print("Вихідна матриця:")
print(a)

# перевірка, чи можна знайти обернену матрицю
if np.linalg.det(a) == 0:
    print("Матриця не має оберненої матриці.")
else:
    # знаходження оберненої матриці
    inv_a = np.linalg.inv(a)
    print("Обернена матриця:")
    print(inv_a)

Вихідна матриця:
[[ 5  4]
 [ 8 11]]
Обернена матриця:
[[ 0.47826087 -0.17391304]
 [-0.34782609  0.2173913 ]]


In [10]:
'''9.	Створіть матрицю розміром 3x3,
заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.'''

a = np.random.rand(3, 3)
print(a)

a_transp = np.transpose(a)
print("Транспонована матриця:")
print(a_transp)

[[0.80469228 0.15490753 0.96611257]
 [0.87975991 0.47423882 0.0660796 ]
 [0.05173365 0.9990612  0.19506064]]
Транспонована матриця:
[[0.80469228 0.87975991 0.05173365]
 [0.15490753 0.47423882 0.9990612 ]
 [0.96611257 0.0660796  0.19506064]]


In [11]:
'''10.	Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, 
а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток вектора на матрицю.'''

matrix = np.random.rand(3, 4)
vector = np.random.rand(4)
# Знаходження добутку вектора на матрицю
m = matrix.reshape((4,3)) # зміна розмірності
result = np.dot(vector, m)  
print("Матриця:\n", matrix)
print("\nВектор:\n", vector)
print("\nРезультат добутку вектора на матрицю:\n", result)

Матриця:
 [[0.85224936 0.79429476 0.69607315 0.34151712]
 [0.47283455 0.38770381 0.94182995 0.74739669]
 [0.17746977 0.63630659 0.43651425 0.72222215]]

Вектор:
 [0.16023782 0.7493565  0.65876803 0.00379842]

Результат добутку вектора на матрицю:
 [1.01534507 0.97561681 0.52172033]


In [12]:
'''11.	Створіть матрицю розміром 2x3 та вектор розміром 3, 
заповніть матрицю випадковими дійсними числами від 0 до 1, 
а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток вектора на матрицю.'''

matrix = np.random.rand(2, 3)
vector = np.random.randint(1, 11, size=3)
# Знаходження добутку вектора на матрицю
m = matrix.reshape((3,2)) # зміна розмірності
result = np.dot(vector, m)  
print("Матриця:\n", matrix)
print("\nВектор:\n", vector)
print("\nРезультат добутку вектора на матрицю:\n", result)


Матриця:
 [[0.30899891 0.20635942 0.84712723]
 [0.26244304 0.84488577 0.02595742]]

Вектор:
 [10  9  2]

Результат добутку вектора на матрицю:
 [12.4039057   4.47749645]


In [13]:
'''12.	Створіть дві матриці розміром 4x4, 
заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю всіх елементів обох матриць.'''

a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)
print("Різниця всіх елементів обох матриць,\n", a-b)

Перша матриця:
[[ 1 10  3  4]
 [ 5  9  9 10]
 [ 8  4  9  4]
 [ 1  9  5  7]]
Друга матриця:
[[ 6  4 10  3]
 [ 1  4  8  8]
 [ 2  1  4  2]
 [ 8  1 10  5]]
Різниця всіх елементів обох матриць,
 [[-5  6 -7  1]
 [ 4  5  1  2]
 [ 6  3  5  2]
 [-7  8 -5  2]]


In [14]:
'''13.	Створіть дві матриці розміром 3x3, 
заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму їх елементів.'''
matrix1 = np.random.randint(-1, 1, size=(3, 3))
matrix2 = np.random.randint(-1, 1, size=(3, 3))

# Знаходження суми елементів обох матриць
result = np.sum(matrix1) + np.sum(matrix2)

print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)
print("\nСума елементів матриць:")
print(result)


Перша матриця:
[[-1  0  0]
 [ 0  0 -1]
 [ 0 -1  0]]

Друга матриця:
[[ 0 -1  0]
 [-1  0 -1]
 [ 0 -1  0]]

Сума елементів матриць:
-7


In [16]:
'''14.	Створіть матрицю розміром 9x9, 
заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть кількість парних елементів матриці.'''

# Створення матриці 9x9 з випадковими дійсними числами в діапазоні від -10 до 10
matrix = np.random.randint(-10, 10, size=(9, 9))

# Знаходження кількості парних елементів у матриці
par = np.sum(matrix % 2 == 0)

print("Матриця 9x9:")
print(matrix)
print("\nКількість парних елементів у матриці = ", par)


Матриця 9x9:
[[ -7  -3   9  -5   1   3  -9   9  -5]
 [  5  -6  -2   3   2   9 -10  -2   9]
 [ -9  -7  -3   7   3   3  -7  -1   1]
 [ -9  -5   4   3 -10   6  -9  -4  -6]
 [  8   9   1   2   0  -9  -4  -9   4]
 [ -6   7  -5   5  -2  -4   3   0   5]
 [-10  -6  -8   3  -4  -8   7   8  -3]
 [ -5   2  -9  -4   3  -6  -3   8  -7]
 [ -9  -5  -7   2   4   2   5  -6  -8]]

Кількість парних елементів у матриці =  34


In [19]:
'''15.	Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 
та знайдіть вектор-стовпчик, що містить середнє геометричне значення елементів кожного рядка матриці.'''
matrix = np.random.uniform(-0.5, 0.5, size=(5, 5))
# Знаходимо середнє геометричне значення елементів кожного рядка
geom_means = np.prod(matrix, axis=1) ** (1/5)
geom_means_rounded = np.round(geom_means, 3)
geometric_means_column_vector = geom_means_rounded.reshape(-1, 1)

print("Матриця:")
print(matrix)
print("\nСереднє геометричне значення елементів кожного рядка:")
print(geom_means_rounded)
print("\nВектор-стовпчик з округленими середніми геометричними:")
print(geometric_means_column_vector)

Матриця:
[[ 0.43675242 -0.12568608 -0.29117398  0.34320294  0.28614106]
 [ 0.14166396 -0.0358022  -0.0110754  -0.27990373  0.40090996]
 [ 0.18482406  0.36736752 -0.12450925 -0.45206403 -0.01111026]
 [ 0.21633378 -0.34084601 -0.44363696 -0.49813706 -0.47272271]
 [ 0.02671626  0.23810222  0.34348865  0.21636602  0.1983941 ]]

Середнє геометричне значення елементів кожного рядка:
[0.275   nan   nan 0.378 0.156]

Вектор-стовпчик з округленими середніми геометричними:
[[0.275]
 [  nan]
 [  nan]
 [0.378]
 [0.156]]


C:\Users\user\AppData\Local\Temp\ipykernel_13356\2020240277.py:5: RuntimeWarning: invalid value encountered in power
  geom_means = np.prod(matrix, axis=1) ** (1/5)


In [ ]:
#Висновок
'''Навчились використовувати пакет numpy в обробці векторів і матриць. 
Створювали масиви з різною розмірністю заповненими випадковими числами в діапазоні 
від-до a = np.random.randint(1, 101, (8, 8)).
Ознайомились з атрибутами та типами даних масивів та використали їх на практиці a = np.zeros((3, 3), dtype=int), 
a = np.random.randint(-15, 16, size=7).
Створили масив з послідовністю чисел a = np.arange(3, 100, 5).
Виконували арифметичні операції:
print(a + b)
print(a - b)
print(a * b)
print(a / b).
Агрегували (par = np.sum(matrix % 2 == 0)).
Розмірність вектора або матриці  може бути змінена методом reshape m = matrix.reshape((4,3)) # зміна розмірності.
Транспортували матрицю a_transp = np.transpose(a)
Множили матриці dot_a_b = np.dot(a, b) та дізнались, що множити можна тільки ті матриці, де кількість стовпців першої
матриці дорівнює кількості рядків другої матриці.
Округлювали значення print("\nСереднє арифметичне = ", round(b,2)).


'''